name: Build application

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle
      - name: Install NDK
        run: echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;25.1.8937393"
      - name: Build with Gradle
        run: ./gradlew assemblePhoneDebug assemblePhoneRelease --no-daemon

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: talkback-foss-test
          path: build/outputs/apk/phone/*
